

SELECT A.CIDDOCUMENTO, C.CRAZONSOCIAL CRAZONSOCIAL,CONVERT(DATE,A.CFECHA) CFECHA, A.CSERIEDOCUMENTO, A.CFOLIO,
A.CIDCONCEPTODOCUMENTO, B.CCODIGOCONCEPTO,CNOMBRECONCEPTO,  CONVERT(DATE, CFECHAVENCIMIENTO) CFECHAVENCIMIENTO, CTIPOCAMBIO, CPENDIENTE, A.CTOTAL,
A.CIDMONEDA, DATEDIFF(DAY, CONVERT(DATE, GETDATE()) ,CONVERT(DATE, CFECHAVENCIMIENTO)) DIAS, DATEDIFF(DAY, CONVERT(DATE, CFECHA), CONVERT(DATE,CFECHAVENCIMIENTO)) CDIASCREDITO, CIDPROYECTO
INTO #documentos
FROM admDocumentos A
INNER JOIN admConceptos B ON A.CIDCONCEPTODOCUMENTO = B.CIDCONCEPTODOCUMENTO
INNER JOIN admClientes C ON A.CIDCLIENTEPROVEEDOR = C.CIDCLIENTEPROVEEDOR
WHERE B.CCODIGOCONCEPTO IN (
  SELECT RTRIM(LTRIM(value)) AS code
  FROM STRING_SPLIT(@conceptCodes, ',')
  WHERE RTRIM(LTRIM(value)) <> ''
)
AND CONVERT(DATE, A.CFECHA) BETWEEN @fechaDesde AND @fechaHasta
AND CPENDIENTE > 0


SELECT *, CTOTAL - CPENDIENTE ABONOS
INTO #documentos2
FROM #documentos A


SELECT  A.CIDDOCUMENTO, C.CNOMBREPRODUCTO, C.CCODIGOPRODUCTO, A.CRAZONSOCIAL, A.CDIASCREDITO, SUM(CNETO) CNETO
INTO #detalleProducto
FROM #documentos2 A INNER JOIN admMovimientos B ON A.CIDDOCUMENTO = B.CIDDOCUMENTO
INNER JOIN admProductos C ON B.CIDPRODUCTO = C.CIDPRODUCTO
GROUP BY A.CIDDOCUMENTO, C.CNOMBREPRODUCTO, C.CCODIGOPRODUCTO, A.CRAZONSOCIAL, A.CDIASCREDITO
ORDER BY A.CIDDOCUMENTO



ALTER TABLE #detalleProducto
ADD Categoria VARCHAR(MAX) NULL, Prioridad INT NULL

UPDATE A
SET Categoria = 'CEMENTO', Prioridad = 1
FROM #detalleProducto A
WHERE CNOMBREPRODUCTO LIKE '%CEMENTO%'


UPDATE A
SET Categoria = CNOMBREPRODUCTO, Prioridad = 2
FROM #detalleProducto A
WHERE CNOMBREPRODUCTO LIKE '%GRAVA%'

UPDATE A
SET Categoria = CNOMBREPRODUCTO, Prioridad = 3
FROM #detalleProducto A
WHERE CNOMBREPRODUCTO LIKE '%ARENA%'

UPDATE A
SET Categoria = CNOMBREPRODUCTO, Prioridad = 4
FROM #detalleProducto A
WHERE CNOMBREPRODUCTO LIKE '%AGUA%'

UPDATE A
SET Categoria = 'ADITIVO', Prioridad = 5
FROM #detalleProducto A
WHERE CNOMBREPRODUCTO LIKE '%ADITIVO%'

UPDATE A
SET Categoria = 'ADITIVO', Prioridad = 5
FROM #detalleProducto A
WHERE CNOMBREPRODUCTO LIKE '%ADIVITO%'


SELECT *  INTO #SinCategoria FROM #detalleProducto WHERE CATEGORIA  IS NULL

SELECT A.*, ROW_NUMBER() OVER(PARTITION BY A.CIDDOCUMENTO ORDER BY A.CNETO DESC) Fila, B.CIDDOCUMENTO IDDOCUMENTOSINCATEGORIA, B.CCODIGOPRODUCTO CCODIGOSINCATEGORIA
INTO #categoriasAgregar
FROM #detalleProducto A INNER JOIN #SinCategoria B ON A.CIDDOCUMENTO = B.CIDDOCUMENTO
WHERE A.Categoria IS NOT NULL


UPDATE A
SET Categoria = B.Categoria, Prioridad = B.Prioridad
FROM #detalleProducto A INNER JOIN #categoriasAgregar B ON A.CIDDOCUMENTO = B.CIDDOCUMENTO
WHERE B.Fila = 1 AND A.Categoria IS NULL


UPDATE A
SET Categoria = CNOMBREPRODUCTO, Prioridad = 666
FROM #detalleProducto A
WHERE Categoria IS NULL

SELECT  A.CIDDOCUMENTO, CRAZONSOCIAL, CATEGORIA, PRIORIDAD, SUM(CNETO) CNETO
INTO #detalleProducto2
FROM #detalleProducto A
GROUP BY A.CIDDOCUMENTO, CRAZONSOCIAL, CATEGORIA, PRIORIDAD

SELECT A.CIDDOCUMENTO, A.CRAZONSOCIAL, A.CATEGORIA, A.PRIORIDAD, ROW_NUMBER() OVER(PARTITION BY CIDDOCUMENTO ORDER BY CNETO DESC) Fila
INTO #detalleProducto3
FROM #detalleProducto2 A


DELETE FROM #detalleProducto3 WHERE Fila > 1

SELECT A.*, B.Categoria, B.Prioridad
INTO #documentos3
FROM #documentos2 A INNER JOIN #detalleProducto3 B ON A.CIDDOCUMENTO = B.CIDDOCUMENTO
ORDER BY A.CRAZONSOCIAL, B.Prioridad

UPDATE #documentos3 SET CTOTAL = CPENDIENTE


UPDATE A SET Categoria = C.CNOMBREPROYECTO FROM #documentos3 A INNER JOIN admDocumentos B ON A.CIDDOCUMENTO = B.CIDDOCUMENTO
INNER JOIN admProyectos C ON B.CIDPROYECTO = C.CIDPROYECTO
WHERE B.CIDPROYECTO IN (8,9)


ALTER TABLE #documentos3
ADD Hoja VARCHAR(100) NULL

UPDATE #documentos3 SET Hoja = 'PLANTA 1' WHERE CNOMBRECONCEPTO LIKE '%1-%'
UPDATE #documentos3 SET Hoja = 'PLANTA 2' WHERE CNOMBRECONCEPTO LIKE '%2-%'
UPDATE #documentos3 SET Hoja = 'PLANTA 3' WHERE CNOMBRECONCEPTO LIKE '%3-%'
UPDATE #documentos3 SET Hoja = 'PLANTA 4' WHERE CNOMBRECONCEPTO LIKE '%4-%'
UPDATE #documentos3 SET Hoja = 'PLANTA 1' WHERE CNOMBRECONCEPTO LIKE '%JIANXING%'
UPDATE #documentos3 SET Hoja = 'PLANTA 5' WHERE CNOMBRECONCEPTO LIKE '%5%'
UPDATE #documentos3 SET Hoja = 'PLANTA 5' WHERE CNOMBRECONCEPTO LIKE '%5%'

UPDATE #documentos3 SET Hoja = 'OTROS' WHERE Hoja IS NULL

SELECT * FROM #documentos3
